/**
 * @hyprdrive/ts-client — Auto-generated TypeScript bindings
 *
 * This package contains TypeScript types and React hooks
 * auto-generated from Rust types via Specta + rspc.
 *
 * DO NOT EDIT MANUALLY — types are regenerated on `cargo build`.
 *
 * Usage:
 *   import { useQuery, useMutation } from '@hyprdrive/ts-client';
 *   const { data } = useQuery(['files.list', { path: '/photos' }]);
 */

// TODO: This file will be auto-generated by rspc + Specta
// Placeholder types until rspc is integrated in Phase 9

export interface File {
    id: string;
    name: string;
    size: number;
    kind: 'file' | 'directory' | 'symlink';
    extension?: string;
    createdAt: string;
    modifiedAt: string;
}

export interface ListFilesQuery {
    parentId?: string;
    sortBy?: string;
    sortDir?: 'asc' | 'desc';
    cursor?: string;
    limit?: number;
}
